image: "anchorfree/k8s-rumors:v1.0.0"
env:
- name: SECRET_NAMESPACE
  value: secrets
- name: SECRET_LABEL
  value: rumored
- name: SECRET_PATCH_LABEL
  value: patch_secret
- name: SECRET_ANNOTATION
  value: "rumors/namespaces"
